"""enforce_not_null_constraints

Revision ID: 7f801634afc7
Revises: 0007
Create Date: 2026-09-15 14:14:30.493899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idempotency_keys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('idempotency_keys', 'fingerprint',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('idempotency_keys', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('idempotency_keys', 'response_body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('login_attempts', 'rate_key',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('login_attempts', 'attempted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('report_records', 'kind',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('report_records', 'fmt',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('report_records', 'label',
               existing_type=sa.VARCHAR(length=160),
               nullable=False)
    op.alter_column('report_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('revoked_jtis', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('revoked_jtis', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('revoked_jtis', 'reason',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'consumed'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revoked_jtis', 'reason',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'consumed'::character varying"))
    op.alter_column('revoked_jtis', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('revoked_jtis', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('report_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('report_records', 'label',
               existing_type=sa.VARCHAR(length=160),
               nullable=True)
    op.alter_column('report_records', 'fmt',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('report_records', 'kind',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('login_attempts', 'attempted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('login_attempts', 'rate_key',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('idempotency_keys', 'response_body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('idempotency_keys', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('idempotency_keys', 'fingerprint',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('idempotency_keys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
